### ISSUE TITLE
Cantilever Plate

### ISSUE THREAD

**Issue by liuyuanhao** [rafavzqz/geopdes#18] opened 2020-11-20 13:46 UTC
Dear Rafa,
Thank you for your previous help.
I would like to implement some strain computation of Cantilever Plate,but I cannot find it.Like the following image.
![image](https://user-images.githubusercontent.com/44806441/99806659-4d215780-2b79-11eb-8f17-6e6ffada03b7.png)
I only find the ex_kirchhoff_rectangular_plate.m in the folder geopdes-master\geopdes-master\geopdes\inst\examples\elasticity.
The plate is the rectangle plate.If the GeoPDEs source code has the above function,please tell me about that.
Would you give me some guidance,please?
Thank you so much.
Deeply grateful,
Jim

**Comment by rafavzqz** [comment] 2020-11-20 14:25
Dear Jim,
I think the formulation of the problem is the one for Kirchhoff-Love 
shell, which is the same you were using for the Scordelis-Lo roof. In 
the repository (not in the package to download) you have an 
implementation of Kirchhoff-Love shlles done by Luca Coradello and Pablo 
Antolin. You will need to modify the geometry and boundary conditions 
for this particular example, but nothing else.

Best,
Rafa

**Comment by liuyuanhao** [comment] 2020-11-21 00:22
Dear Rafa,
Thank you so much！
Could you tell me where is the repository？Is it in the code GeoPdes？If I modify the code about lo-roof can solve this problem？
Deeply Grateful,
Jim

**Comment by rafavzqz** [comment] 2020-11-23 11:54
Dear Jim,
yes, modifying the code should be enough, if you want to use the 
Kichhoff-Love shell formulation. The code is in the Geopdes repository 
in github.
https://github.com/rafavzqz/geopdes

Best,
Rafa

**Comment by liuyuanhao** [comment] 2020-11-23 12:34
Thank you so much!!

Deeply Grateful,
Jim

**Comment by liuyuanhao** [comment] 2021-01-22 02:13
Dear Rafa,
Thank you for your previous help.
![image](https://user-images.githubusercontent.com/44806441/105436408-1ad7c780-5c9a-11eb-9410-92c5e22fa30b.png)

Could you tell me how to fix the second row of the points？Should I fix the points before compute the stiffness matrix and external force or after them?
Deeply Grateful,
Jim

**Comment by rafavzqz** [comment] 2021-01-22 08:39
Dear Jim,
yes, I guess so: the geometry should be fixed before assembling the 
linear system. However, this is not a question about the implementation 
in geopdes, it is a question about the method itself, so you should 
probably ask the authors of the paper.

Best,
Rafa

**Closed as completed** 2021-05-04 08:07 UTC
